### ISSUE TITLE
rms should not assume model is workshared

### ISSUE THREAD

**Issue by eirannejad** [hdm-dt-fb/rvt_model_services#4]
Journal detachment requirement causes errors on normal models:
` Jrn.Data "FileOpenSubDialog" , "DetachCheckBox", "True"`

**Comment by fbe-work** [comment]
That was the default I started with(since I was only interested in monitoring our workshared models), and thought I would add a switch for non-workshared. But it could be done the other way around as well. 
It is basically that line in the journal template or a different journal template that I need to tie to an optional docopt switch.

**Comment by fbe-work** [comment]
..but it also touches on another important topic, which is the composition of journal files. 
I need to generalize this composition, so things like detach/ws-file or audit become more easy to activate optional switches, rather than a whole separate command package..
what is tricky is that they sometimes are not clean building blocks but interleave. 
example open file detached:
the option needs to be checked at opening file, but the TaskDialogResult will appear later after specifying the path and a potential audit block..
so I guess it will take some time to get this cleanly assembled.

**Comment by eirannejad** [comment]
I think this is resolved with the adoption of `rjm` as it has separate methods for workshared and non-workshared models.
